### ISSUE TITLE
Bash complains about 'default: command not found' on first run

### ISSUE THREAD

**Issue by funollet** [rsteube/lazycomplete#23]
I configured lazycomplete for several bash completions, as in

    source <(lazycomplete \                                                                            
        kubectl 'kubectl completion bash' \
    )

The first time it tries to autocomplete bash complains.

    $ kubectl <TAB>bash: default: command not found

Press tab again and completion seems to work as expected.

- lazycomplete: 0.0.18
- bash: 5.2.2(1)-release

**Comment by rsteube** [comment]
Completion is registered by kubectl with an additional `-o default` and `lazycomplete` currently just grabs the third word (which is wrong):
```sh
# complete -o default -F __start_kubectl kubectl
$"$(complete -p kubectl | awk '{print $3}')"
```
