### ISSUE TITLE
Discussions

### ISSUE THREAD

**Issue by maxlandon** [rsteube/lazycomplete#25]
Hello rsteube, is there a way to reach you somewhere ?
Me: maximelandon@gmail.com (can you delete this issue once read ?  thanks a lot :) )
Alternatively: A slack channel on where I hang, join the #golang one and I'll ping you: bloodhoundhq.slack.com

About a proposal I'm about (will have by the time you read this probably) to open on the cobra repo.
Thanks !

**Comment by rsteube** [comment]
@maxlandon  Matrix mostly: @rsteube:matrix.org. Also on discord, not on slack yet but will probably add that one as well.
